# Generated by Django 5.0 on 2026-01-14 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VentureProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("industry_sector", models.CharField(max_length=100)),
                ("website", models.URLField()),
                ("linkedin_url", models.URLField()),
                ("address", models.TextField(blank=True, null=True)),
                ("year_founded", models.IntegerField(blank=True, null=True)),
                ("employees_count", models.IntegerField(blank=True, null=True)),
                ("short_description", models.TextField()),
                ("problem_statement", models.TextField()),
                ("solution_description", models.TextField()),
                ("target_market", models.TextField()),
                ("traction_metrics", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venture_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "venture_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VentureNeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "need_type",
                    models.CharField(
                        choices=[
                            ("FINANCE", "Finance"),
                            ("MARKET_ACCESS", "Market Access"),
                            ("EXPERT", "Expert"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "finance_size_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("finance_objectives", models.TextField(blank=True, null=True)),
                ("target_markets", models.JSONField(blank=True, null=True)),
                (
                    "expertise_field",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("other_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "venture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="needs",
                        to="ventures.ventureprofile",
                    ),
                ),
            ],
            options={
                "db_table": "venture_needs",
            },
        ),
        migrations.CreateModel(
            name="VentureDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("PITCH_DECK", "Pitch Deck"), ("OTHER", "Other")],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="ventures/documents/")),
                ("file_size", models.IntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "venture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="ventures.ventureprofile",
                    ),
                ),
            ],
            options={
                "db_table": "venture_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role_title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "venture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="ventures.ventureprofile",
                    ),
                ),
            ],
            options={
                "db_table": "team_members",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("linkedin_url", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("role_title", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "venture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founders",
                        to="ventures.ventureprofile",
                    ),
                ),
            ],
            options={
                "db_table": "founders",
                "ordering": ["created_at"],
            },
        ),
    ]
