# Generated by Django 5.0 on 2026-01-14 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ventures", "0002_auto_20260114_1601"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ventureproduct",
            new_name="venture_pro_user_id_c2ba48_idx",
            old_name="venture_pro_user_sta_idx",
        ),
        migrations.RenameIndex(
            model_name="ventureproduct",
            new_name="venture_pro_user_id_5a7a21_idx",
            old_name="venture_pro_user_act_idx",
        ),
    ]
