# Generated by Django 5.0 on 2026-01-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ventures",
            "0003_rename_venture_pro_user_sta_idx_venture_pro_user_id_c2ba48_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ventureproduct",
            name="problem_statement",
        ),
        migrations.RemoveField(
            model_name="ventureproduct",
            name="solution_description",
        ),
        migrations.RemoveField(
            model_name="ventureproduct",
            name="target_market",
        ),
        migrations.RemoveField(
            model_name="ventureproduct",
            name="traction_metrics",
        ),
        migrations.AddField(
            model_name="venturedocument",
            name="funding_amount",
            field=models.CharField(
                blank=True,
                help_text="Funding amount (e.g., $2M)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venturedocument",
            name="funding_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRE_SEED", "Pre-Seed"),
                    ("SEED", "Seed"),
                    ("SERIES_A", "Series A"),
                    ("SERIES_B", "Series B"),
                    ("SERIES_C", "Series C"),
                    ("GROWTH", "Growth"),
                ],
                help_text="Funding stage",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venturedocument",
            name="problem_statement",
            field=models.TextField(
                blank=True, help_text="What problem does your product solve?", null=True
            ),
        ),
        migrations.AddField(
            model_name="venturedocument",
            name="solution_description",
            field=models.TextField(
                blank=True,
                help_text="How does your product solve this problem?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venturedocument",
            name="target_market",
            field=models.TextField(
                blank=True, help_text="Describe your target market", null=True
            ),
        ),
        migrations.AddField(
            model_name="venturedocument",
            name="traction_metrics",
            field=models.JSONField(
                blank=True,
                help_text="Current traction, metrics, and achievements",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venturedocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="venturedocument",
            name="use_of_funds",
            field=models.TextField(
                blank=True, help_text="How will the funds be used?", null=True
            ),
        ),
    ]
