# Generated by Django 5.0 on 2026-01-15 23:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ventures", "0005_pitch_deck_access_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pitchdeckaccess",
            name="pitch_deck_access_unique_document_investor",
        ),
        migrations.RenameIndex(
            model_name="pitchdeckaccess",
            new_name="pitch_deck__documen_90b3e9_idx",
            old_name="pitch_deck_access_doc_idx",
        ),
        migrations.RenameIndex(
            model_name="pitchdeckaccess",
            new_name="pitch_deck__investo_88fbbf_idx",
            old_name="pitch_deck_access_inv_idx",
        ),
        migrations.RenameIndex(
            model_name="pitchdeckaccessevent",
            new_name="pitch_deck__documen_4c5968_idx",
            old_name="pitch_deck_event_doc_at_idx",
        ),
        migrations.RenameIndex(
            model_name="pitchdeckaccessevent",
            new_name="pitch_deck__user_id_1ce90e_idx",
            old_name="pitch_deck_event_user_idx",
        ),
        migrations.RenameIndex(
            model_name="pitchdeckaccessevent",
            new_name="pitch_deck__documen_22f96e_idx",
            old_name="pitch_deck_event_doc_type_idx",
        ),
        migrations.RenameIndex(
            model_name="pitchdeckrequest",
            new_name="pitch_deck__documen_24c183_idx",
            old_name="pitch_deck_req_doc_idx",
        ),
        migrations.RenameIndex(
            model_name="pitchdeckrequest",
            new_name="pitch_deck__investo_36115f_idx",
            old_name="pitch_deck_req_inv_idx",
        ),
        migrations.RenameIndex(
            model_name="pitchdeckrequest",
            new_name="pitch_deck__status_dab3d9_idx",
            old_name="pitch_deck_req_status_idx",
        ),
        migrations.RenameIndex(
            model_name="pitchdeckshare",
            new_name="pitch_deck__documen_2d4e77_idx",
            old_name="pitch_deck_share_doc_idx",
        ),
        migrations.RenameIndex(
            model_name="pitchdeckshare",
            new_name="pitch_deck__investo_dcd41c_idx",
            old_name="pitch_deck_share_inv_idx",
        ),
        migrations.AlterUniqueTogether(
            name="pitchdeckaccess",
            unique_together={("document", "investor")},
        ),
    ]
