# Generated by Django 5.0 on 2026-01-16 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ventures",
            "0006_remove_pitchdeckaccess_pitch_deck_access_unique_document_investor_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VentureProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("year_founded", models.IntegerField(blank=True, null=True)),
                ("employees_count", models.IntegerField(blank=True, null=True)),
                (
                    "founder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("founder_linkedin", models.URLField(blank=True, null=True)),
                (
                    "founder_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("customers", models.TextField(blank=True, null=True)),
                ("key_metrics", models.TextField(blank=True, null=True)),
                ("needs", models.JSONField(blank=True, default=list, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="ventures/profiles/logos/"
                    ),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venture_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "venture_profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="venture_pro_user_id_0bbf12_idx")
                ],
            },
        ),
    ]
