# Generated by Django 5.0 on 2026-01-19 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventures", "0007_ventureprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentCommitment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EXPRESSED", "Interest Expressed"),
                            ("COMMITTED", "Committed"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="EXPRESSED",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Intended investment amount",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from investor",
                        null=True,
                    ),
                ),
                ("committed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="ventures.venturedocument",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_commitments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_commitments",
                        to="ventures.ventureproduct",
                    ),
                ),
            ],
            options={
                "db_table": "investment_commitments",
                "ordering": ["-committed_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "investor", "status"],
                        name="investment__documen_2fe35e_idx",
                    ),
                    models.Index(
                        fields=["investor", "status"],
                        name="investment__investo_f5cfd6_idx",
                    ),
                    models.Index(
                        fields=["product", "status"],
                        name="investment__product_62c75a_idx",
                    ),
                ],
                "unique_together": {("document", "investor")},
            },
        ),
        migrations.CreateModel(
            name="PitchDeckInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("interested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes from investor about their interest",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False if investor unfollowed"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="ventures.venturedocument",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitch_deck_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pitch_deck_interests",
                "ordering": ["-interested_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "investor", "is_active"],
                        name="pitch_deck__documen_f1bdd4_idx",
                    ),
                    models.Index(
                        fields=["investor", "is_active"],
                        name="pitch_deck__investo_f48c54_idx",
                    ),
                ],
                "unique_together": {("document", "investor")},
            },
        ),
    ]
