# Generated by Django 5.0 on 2026-01-19 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventures", "0008_add_pitch_deck_interest_and_investment_commitment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentcommitment",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Venture user who responded to the commitment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_commitments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="investmentcommitment",
            name="venture_response",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("RENEGOTIATE", "Renegotiate"),
                ],
                default="PENDING",
                help_text="Venture's response to the investment commitment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="investmentcommitment",
            name="venture_response_at",
            field=models.DateTimeField(
                blank=True, help_text="When venture responded", null=True
            ),
        ),
        migrations.AddField(
            model_name="investmentcommitment",
            name="venture_response_message",
            field=models.TextField(
                blank=True,
                help_text="Optional message from venture (e.g., counter-offer, terms discussion)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="investmentcommitment",
            index=models.Index(
                fields=["product", "venture_response"],
                name="investment__product_d14c09_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investmentcommitment",
            index=models.Index(
                fields=["venture_response", "venture_response_at"],
                name="investment__venture_6a6a18_idx",
            ),
        ),
    ]
