# Generated by Django 5.0 on 2026-01-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
        ("ventures", "0009_add_venture_response_to_investment_commitment"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentcommitment",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked conversation for negotiation correspondence",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commitments",
                to="messaging.conversation",
            ),
        ),
    ]
