# Generated by Django 5.0 on 2026-01-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_rename_venture_to_product"),
        (
            "ventures",
            "0003_rename_venture_pro_user_sta_idx_venture_pro_user_id_c2ba48_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="successstory",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="success_stories",
                to="ventures.ventureproduct",
            ),
        ),
    ]
