# Generated by Django 5.0 on 2026-01-14 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ventures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("INVESTOR", "Investor"), ("MENTOR", "Mentor")],
                        max_length=20,
                    ),
                ),
                ("target_object_id", models.UUIDField()),
                ("score", models.IntegerField(default=0)),
                ("reasons", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
                (
                    "venture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="ventures.ventureproduct",
                    ),
                ),
            ],
            options={
                "db_table": "matches",
                "ordering": ["-score", "-refreshed_at"],
                "indexes": [
                    models.Index(
                        fields=["venture", "target_type"],
                        name="matches_venture_3b2de4_idx",
                    ),
                    models.Index(fields=["score"], name="matches_score_aa87f8_idx"),
                ],
            },
        ),
    ]
