# Generated by Django 5.0 on 2026-01-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0002_rename_venture_to_product"),
        (
            "ventures",
            "0003_rename_venture_pro_user_sta_idx_venture_pro_user_id_c2ba48_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="match",
            new_name="matches_product_105188_idx",
            old_name="matches_product_target_idx",
        ),
        migrations.AlterField(
            model_name="match",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="ventures.ventureproduct",
            ),
        ),
    ]
