# Generated by Django 5.0 on 2026-01-15 09:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorVisibleToVenture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "investor_visible_to_ventures",
            },
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="deals_count",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="investment_experience_years",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddIndex(
            model_name="investorprofile",
            index=models.Index(
                fields=["status", "visible_to_ventures"],
                name="investor_pr_status_bfb212_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investorprofile",
            index=models.Index(fields=["user"], name="investor_pr_user_id_f9ba5a_idx"),
        ),
        migrations.AddField(
            model_name="investorvisibletoventure",
            name="investor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visibility_grants",
                to="investors.investorprofile",
            ),
        ),
        migrations.AddField(
            model_name="investorvisibletoventure",
            name="venture_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visible_investors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="investorvisibletoventure",
            index=models.Index(
                fields=["investor", "venture_user"],
                name="investor_vi_investo_073dc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investorvisibletoventure",
            index=models.Index(
                fields=["venture_user"], name="investor_vi_venture_649750_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="investorvisibletoventure",
            unique_together={("investor", "venture_user")},
        ),
    ]
