# Generated by Django 5.0 on 2026-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investors", "0002_investorvisibletoventure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorprofile",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Location/address (City, State, Country)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Professional bio describing background and interests",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="investment_experience",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of investment experience, notable deals, etc.",
                null=True,
            ),
        ),
    ]
