# Generated by Django 5.0 on 2026-01-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investors", "0003_investorprofile_address_investorprofile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorprofile",
            name="allow_direct_contact",
            field=models.BooleanField(
                default=True, help_text="Allow ventures to contact directly"
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="geographic_focus",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Geographic regions of interest (e.g., ['North America', 'Europe'])",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="investment_philosophy",
            field=models.TextField(
                blank=True,
                help_text="Investment philosophy and what you look for in startups",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="investor_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INDIVIDUAL", "Individual"),
                    ("FIRM", "Firm"),
                    ("CORPORATE", "Corporate"),
                    ("FAMILY_OFFICE", "Family Office"),
                ],
                help_text="Type of investor: Individual, Firm, Corporate, or Family Office",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="linkedin_url",
            field=models.URLField(
                blank=True, help_text="LinkedIn profile URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="max_investment",
            field=models.CharField(
                blank=True,
                help_text="Maximum investment amount (e.g., '5m', '$10M')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="min_investment",
            field=models.CharField(
                blank=True,
                help_text="Minimum investment amount (e.g., '100k', '$500K')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="notable_investments",
            field=models.TextField(
                blank=True,
                help_text="Notable investments and portfolio companies",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="website",
            field=models.URLField(
                blank=True, help_text="Company or personal website URL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="linkedin_or_website",
            field=models.URLField(
                blank=True,
                help_text="Legacy field - use website and linkedin_url instead",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="visible_to_ventures",
            field=models.BooleanField(
                default=False, help_text="Make profile visible to ventures"
            ),
        ),
    ]
