# Generated by Django 5.0 on 2026-01-14 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("linkedin_or_website", models.URLField()),
                ("contact_email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("expertise_fields", models.JSONField(default=list)),
                ("experience_overview", models.TextField()),
                ("industries_of_interest", models.JSONField(default=list)),
                (
                    "engagement_type",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("PRO_BONO", "Pro Bono"),
                            ("BOTH", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "paid_rate_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("DAILY", "Daily"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "paid_rate_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("availability_types", models.JSONField(default=list)),
                (
                    "preferred_engagement",
                    models.CharField(
                        choices=[
                            ("VIRTUAL", "Virtual"),
                            ("IN_PERSON", "In Person"),
                            ("BOTH", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("visible_to_ventures", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mentor_profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
